# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Hungry' do
  pod 'Firebase/Auth'
  use_frameworks!
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'FacebookCore'
end


